version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
